defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

num_actor: 10

rl:
  # learning rate
  lr: 1e-4
  lr_dcay: 0.90
  # batch size
  batch_sz: 64
  # decay factor
  gamma: .99
  # epsilon greedy
  eps_max: 1
  eps_min: .1
  #  eps_decay: 1e-6
  eps_decay: 1e-3
  # n-step TD error
  n_step: 1
  # randomizer seed
  seed: 999
  # DQN parameters
  ## target network update frequency
  update_freq: 500
  ## soft update
  tau: .95
  # Replay buffer parameters
  replay_sz: 6000000
  init_replay_num: 5e4
  beta_decay_step: 60000
  beta_init: .7
  # device cpu or cuda
  device: 'cuda'
  actor_device: 'cpu'
  # Ape-x DQN
  ## periodically send data to replay.
  send_period: 10
  # save checkpoint
  ## period
  save_period: 500
  sync_dqn_freq: 50

ddqn:
  num_res_block: 2
  num_filters: 18
  head_channels_adv: 4
  head_channels_val: 4
  manifest_emb_dim: 64

eval:
  eval_num: 200
  reset_multiplier: 1.5
  reset_multiplier2: 2
  reset_evolve: 13
  eval_interval: 15
  device: 'cuda'
  state_level: 2
  class_level: 1
  pass_rate: 0.97

env:
  pallet_dimensions: [ 10, 10, 10 ]
  sku: 5
  seed: 888




